### ISSUE TITLE
Текст текущего играющего трека (в радио)

### ISSUE THREAD

**Issue by umk0** [lodo4nik/Yandex-Music-Discord-RPC#1]
К сожалению метод описанный тут https://yandex-music.readthedocs.io/en/main/examples.lyrics_playing_track.html не работает если клиент слушает радио. Можно ли как то узнать какой трек слушает клиент в радио?

**Comment by lodo4nik** [comment]
Насколько я знаю, в Yandex Music API нет почти ничего, связанного с радио. Можно попробовать порыться в документации
